config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard'
  resources :users, only: [:show, :update]

  patch '/add_friend', to: 'users#add_friend'
  patch '/accept/:id', to: 'users#accept_friend', as: :accept
  patch '/reject/:id', to: 'users#reject_friend', as: :reject

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :person, foreign_key: 'user_id', class_name: 'User'
  belongs_to :friend, foreign_key: 'friend_id', class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_friend_code
  after_create :generate_bday_event
  after_save :generate_bday_event
  has_secure_password

  has_many :friendships, foreign_key: 'user_id', class_name: 'Friendship'
  has_many :friends, through: :friendships
  
  validates :username, :name, presence: true

  def befriend(user)
    self.friends << user
    user.friends << self

    Friendship.find_by(user_id: user.id, friend_id: self.id).update(is_request: true)
  end

  private
  def generate_friend_code
    begin
      random_code_1 = SecureRandom.alphanumeric(4).upcase
      random_code_2 = SecureRandom.alphanumeric(4).upcase
      self.friend_code = "#{random_code_1}-#{random_code_2}"
    end while User.exists?(friend_code: self.friend_code)
  end

  def generate_bday_event
    if not self.bday.nil? || attribute_changed?(:bday)
      if Event.exists?(owner: self.id)
        Event.find_by(owner: self.id).update(start_time: self.bday)

      else
        Event.create(name: "🎂 #{self.name}'s Birthday", start_time: self.bday, owner: self.id)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end
end

app/controllers/pages_controller.rb
require 'pry'
class PagesController < ApplicationController
  before_action :authenticate

  def dashboard
    request_friendship_list = helpers.get_request_friendship_list
    @events = get_bday(params[:start_date])
    @all_events = get_all_bday
    @request_friend_list = []
    request_friendship_list.each do |request|
      @request_friend_list << User.find(request.friend_id)
    end
  end

  private
  def authenticate
    redirect_to login_path if not current_user
  end

  def get_bday(request_date)
    bdays = []
    friend_ids = current_user.friends.pluck(:id) << current_user.id
    request_date = request_date.nil? ? Time.now : Date.parse(request_date) 

    bdays_in_requested_month = Event.where("EXTRACT(MONTH from start_time) = ? AND owner IN (?)", request_date.month, friend_ids)
    bdays_in_requested_month.each do |bday|
      if current_user.id != bday.owner && Friendship.find_by(user_id: current_user.id, friend_id: bday.owner).confirmation == false
        next
      end
      bday.name = "🎂 Your Birthday" if bday.owner == current_user.id
      bday.start_time = bday.start_time.change(year: request_date.year)
      bdays << bday
    end
    bdays
  end

  def get_all_bday
    bdays = []
    friend_ids = current_user.friends.pluck(:id) << current_user.id
    all_friend_bdays = Event.where("owner IN (?)", friend_ids)

    all_friend_bdays.each do |bday|
      if current_user.id != bday.owner && Friendship.find_by(user_id: current_user.id, friend_id: bday.owner).confirmation == false
        next
      end
      bday.name = "🎂 Your Birthday" if bday.owner == current_user.id
      bday.start_time = bday.start_time.change(year: Time.now.year)
      bdays << bday
    end
    bdays
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid username or password!"
      render :new, status: :unauthorized
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to login_path, status: :see_other
  end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.username = user_params[:username]
    @user.name = user_params[:name]
    @user.bday = user_params[:bday]
    @user.email = user_params[:email]
    if not user_params[:password].blank?
      if @user.authenticate(user_params[:password])
        @user.password = user_params[:new_password]
      else
        flash.now[:alert] = "Old password is wrong. Please try again."
        render :show, locals: {user: @user}, status: :unprocessable_entity
        return
      end
    end
    if @user.save
      flash[:notice] = "Account update successfully!"
    else
      flash[:alert] = "All required field must be filled!"
    end
    redirect_to fallback_location: user_path(@user)
  end

  def add_friend
    if User.exists?(friend_code: friend_params[:new_friend_code])
      friend = User.find_by_friend_code(friend_params[:new_friend_code])
      current_user.befriend(friend)
      flash[:notice] = "Waiting for your friend's approval."
      redirect_to root_path
    else
      flash[:alert] = "Friend code is invalid."
      redirect_to root_path
    end
  end

  def accept_friend
    Friendship.find_by(user_id: current_user.id, friend_id: params[:id]).update(confirmation: true)
    Friendship.find_by(user_id: params[:id], friend_id: current_user.id).update(confirmation: true)
    redirect_to root_path
  end

  def reject_friend
    Friendship.find_by(user_id: current_user.id, friend_id: params[:id]).destroy
    Friendship.find_by(user_id: params[:id], friend_id: current_user.id).destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :name, :email, :bday, :password, :new_password)
  end

  def friend_params
    params.require(:user).permit(:new_friend_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def get_profile_letters(name)
    if name.split.length > 1
      return name.split[-2..-1].map {|word| word[0].upcase}.join
    else
      return name[0].upcase
    end
  end

  def is_waiting_for_accepted_friend?(friend_id)
    Friendship.find_by(user_id: current_user.id, friend_id: friend_id).confirmation == false
  end

  def get_request_friendship_list
    Friendship.where(user_id: current_user.id, is_request: true)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharecake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main_content">
      <% unless request.path == login_path %>
        <%= render 'shared/header'%>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_event_container.html.erb
<h2>Upcoming events</h2>
<div class="events_list">
  <% @all_events.each do |event| %>
    <div class="event_item">
      <span>
        🗓️ <%= event.start_time.strftime("%d/%m/%Y") %>
      </span>
      <%= event.name %>
    </div>
  <% end %>
</div>

app/views/pages/_friend_container.html.erb
<h2>Add your friend</h2>
<%= form_with model: user, url: add_friend_path, method: :patch, class: "friend_code_form" do |f| %>
  <% if flash[:alert] %>
    <div class="alert_container">
      <%= flash[:alert] %>
    </div>
  <% end %>    
  <% if flash[:notice] %>
    <div class="notice_container">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <%= f.text_field :new_friend_code, placeholder: "Your friend's code" %>
  <%= f.submit "Add", style: "margin-top: 0.2em;" %>
<% end %>
<h2>Request List</h2>
<ul class="friend_list">
  <% @request_friend_list.each do |friend|%>
    <% if is_waiting_for_accepted_friend?(friend.id) %>
      <li>
        <%= friend.name %>
          <div>
            <%= button_to "Accept" , accept_path(friend), method: :patch, class: 'accept_button' %>
            <%= button_to "Reject" , reject_path(friend), method: :patch, class: 'reject_button' %>
          </div>
      </li>
    <% end %>
  <% end %>
</ul>
<h2>Friend List</h2>
<ul class="friend_list">
<% user.friends.each do |friend|%>
  <% if not is_waiting_for_accepted_friend?(friend.id) %>
    <li class="accepted_friend" >
      <%= friend.name %>
      <%= button_to "Unfriend" , reject_path(friend), method: :patch, form: {data: {turbo_confirm: "Unfriend with #{friend.name}"}}, class: 'reject_button' %>
    </li>
  <% end %>
<% end %>
</ul>

app/views/pages/dashboard.html.erb
<div class="main_container">
  <div class="friend_container">
    <%= render 'pages/friend_container', user: current_user %>
  </div>
  <div class="calendar_container">
    <%= month_calendar(events: @events) do |date, events| %>
      <%= date.day %>
      <% events.each do |event| %>
        <div class="event">
          <%= event.name %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="event_container">
    <%= render 'pages/event_container' %>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header" data-controller="header">
  <div>
    <%= link_to root_path do%>
      <%= render 'shared/logo' %>
    <% end %>
  </div>
  <div class="user_container">
    <div class="user_default_picture">
      <%= get_profile_letters(current_user.name) %>
    </div>
    <%= current_user.name %> 
    <%= image_tag 'dropdown', class: "icon", data: {action: "click->header#toggle"} %>
    <div class="user_actions_modal" data-header-target="modal">
      <span>Friend code: <%= current_user.friend_code %></span>
      <div class="user_action">
        <%= image_tag 'account', class: "icon" %>
        <%= link_to "Account", user_path(current_user)%>
      </div>
      <div class="user_action">
        <%= image_tag 'logout', class: "icon" %>
        <%= button_to "Logout", logout_path, method: :delete, form: {data: {turbo_confirm: "Are you sure ?"}} %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_logo.html.erb
<div id="logo">
  <%= image_tag 'icon.svg', id: "logo_img" %>
  <span>ShareCake</span>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>Account Settings</h2>
  <%= form_with model: @user, url: user_path(@user), method: :patch do |f|%>
    <% if flash.now[:alert] %>
      <div class="alert_container">
        <%= flash.now[:alert] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice_container">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= f.label "Username" %>
    <%= f.text_field :username %>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <%= f.label "Email" %>
    <%= f.email_field :email, placeholder: "Set your email" %>
    <%= f.label "Birthday" %>
    <%= f.date_field :bday, placeholder: "Set your birthday" %>
    <%= f.label "Old password" %>
    <%= f.password_field :password, placeholder: "Your old password" %>
    <%= f.label "New password" %>
    <%= f.password_field :new_password, placeholder: "Your new password" %> 
    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>